"""
Pydantic schemas for the real-time presence (listener count) feature.
"""
import re
from pydantic import BaseModel, Field, field_validator

# RFC 4122 UUID pattern (version 1–5)
_UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    re.IGNORECASE,
)


class HeartbeatRequest(BaseModel):
    session_id: str = Field(
        ...,
        min_length=36,
        max_length=36,
        description="Anonymous UUID v4 from sessionStorage",
    )

    @field_validator("session_id")
    @classmethod
    def session_id_must_be_uuid(cls, v: str) -> str:
        if not _UUID_RE.match(v):
            raise ValueError("session_id must be a valid UUID (e.g. generated by crypto.randomUUID())")
        return v.lower()


class ListenerCountResponse(BaseModel):
    count: int = Field(..., ge=0, description="Number of active listeners right now")